import type { ChatProvider } from "./types";

const MAX_SECTION_LENGTH = 2900;

export class SlackProvider implements ChatProvider {
  readonly name = "slack";
  private webhookUrl: string;

  constructor(webhookUrl: string) {
    if (!webhookUrl) {
      throw new Error("Slack webhook URL is required");
    }
    this.webhookUrl = webhookUrl;
  }

  async send(message: string): Promise<void> {
    const text =
      message.length > MAX_SECTION_LENGTH
        ? message.slice(0, MAX_SECTION_LENGTH) + "\n_[truncated]_"
        : message;

    const response = await fetch(this.webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        blocks: [
          {
            type: "header",
            text: {
              type: "plain_text",
              text: "Commit Chronicles - Team Pulse",
              emoji: true,
            },
          },
          {
            type: "section",
            text: {
              type: "mrkdwn",
              text,
            },
          },
          {
            type: "context",
            elements: [
              {
                type: "mrkdwn",
                text: `_Generated by Commit Chronicles at ${new Date().toISOString()}_`,
              },
            ],
          },
        ],
      }),
    });

    if (!response.ok) {
      const body = await response.text();
      throw new Error(`Slack webhook failed (${response.status}): ${body}`);
    }
  }
}
